### ISSUE TITLE
Version incorrectly increased with custom labels

### ISSUE THREAD

**Issue by maxhq** [yanick/Dist-Zilla-Plugin-NextVersion-Semantic#4]
Hi,

I use your wonderful module as follows:

    [NextVersion::Semantic]
    major = *NEW FEATURES, *API CHANGES
    minor = +ENHANCEMENTS
    revision = REVISION, BUG FIXES, DOCUMENTATION
    numify_version = 1
    format = %d.%03d%03d

Now when there is e.g. an entry under [BUG FIXES] and under [+ENHANCEMENTS] in the CHANGES file, still only the "revision" part of the version number is increased.

If there is also an entry under [*NEW FEATURES], the "major part" gets increased correctly.

**Comment by yanick** [comment]
Ooops. Found the bug and pushed the fix. All should be better, now. Thanks! :-)

**Comment by maxhq** [comment]
Great, thank you!
