### ISSUE TITLE
Warnings with perl 5.22.0  "unescaped left brace in regex is deprecated"

### ISSUE THREAD

**Issue by cazador481** [yanick/Dist-Zilla-Plugin-NextVersion-Semantic#5]
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE \$NEXT}}/ at /home/utils/perl5/perlbrew/perls/5.22.0-001/lib/site_perl/5.22.0/Dist/Zilla/Plugin/PreviousVersion/Changelog.pm line 36, <GEN1> line 35.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE \$NEXT}}/ at /home/utils/perl5/perlbrew/perls/5.22.0-001/lib/site_perl/5.22.0/Dist/Zilla/Plugin/NextVersion/Semantic.pm line 89, <GEN1> line 36.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE \$NEXT}}/ at /home/utils/perl5/perlbrew/perls/5.22.0-001/lib/site_perl/5.22.0/Dist/Zilla/Plugin/NextVersion/Semantic.pm line 107, <GEN1> line 36.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE \$NEXT}}/ at /home/utils/perl5/perlbrew/perls/5.22.0-001/lib/site_perl/5.22.0/Dist/Zilla/Plugin/NextVersion/Semantic.pm line 189, <GEN1> line 36.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE \$NEXT}}/ at /home/utils/perl5/perlbrew/perls/5.22.0-001/lib/site_perl/5.22.0/Dist/Zilla/Plugin/NextVersion/Semantic.pm line 218, <GEN1> line 36.
[DZ] building distribution under .build/iBn7ItOv7T for installation
[DZ] beginning to build NV-Hwmeth-Golden
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^(?:(?^x: undef | (?^x: (?^:[0-9]+) (?: \. | (?^:\.[0-9]+) (?^:_[0-9]+)? )?
        |
        (?^:\.[0-9]+) (?^:_[0-9]+)?
    ) | (?^x:
        v (?^:[0-9]+) (?: (?^:\.[0-9]+)+ (?^:_[0-9]+)? )?
        |
        (?^:[0-9]+)? (?^:\.[0-9]+){2,} (?^:_[0-9]+)?
    ) )|(?^:{{ <-- HERE \$NEXT}}))/ at /home/utils/perl5/perlbrew/perls/5.22.0-001/lib/site_perl/5.22.0/CPAN/Changes.pm line 73, <DATA> line 126.
[

**Comment by yanick** [comment]
Fixed, thanks!
