### ISSUE TITLE
Default value of 'format'

### ISSUE THREAD

**Issue by GeekRuthie** [yanick/Dist-Zilla-Plugin-NextVersion-Semantic#7]
The default value of the format parameter causes Perl::Critic::Policy::ValuesAndExpressions::RequireNumericVersion to scream and cry.  I suggest changing the default format to %d.%02d%02d instead.

**Comment by yanick** [comment]
I'm afraid I'll continue to break Perl critic's heart. I am quite in the camp of Major.minor.bump-type of versioning. But I am a magnanimous man :smirk:, and the format is fully customizable via configuration. So having your own go %d.%02d%02d should be trivial.

**Comment by GeekRuthie** [comment]
Fair enough, and already done.  :)
